# Generated by Django 4.2.7 on 2024-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
